spring:
  application:
    name: ecommerce-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kemanedonfack/ecommerce-configurations.git
server:
  port: 8090