apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deploy
  labels:
   app: product-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
      - name: product-service-container
        image: lugar2020/product-service
        ports:
        - containerPort: 8083
        env:
        - name: CONFIG_SERVER
          value: "http://10.0.0.2:30090"
        - name: ENV
          value: "prod"

---

apiVersion: v1
kind: Service
metadata: 
  name: product
  labels:
    name: product-service-service
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
  selector:
    app: product-service-app
